  # Configuration for Label Commenter - https://github.com/peaceiris/actions-label-commenter
labels:
  - name: needs-triaging
    labeled:
      issue:
        body: |
          @{{ issue.user.login }}, thank you for creating this issue. We will troubleshoot it as soon as we can.

          ---
          <details>
            <summary>Info for maintainers</summary>
            <div>
              <br>
              <p>
                Triage this issue by using labels.
              </p>
              <p>
                If information is missing, add a helpful comment and add the <code>I-issue-template</code> label.
              </p>
              <p>
                Thank you!
              </p>
            </div>
          </details>
  - name: I-issue-template
    labeled:
      issue:
        body: |
          Hi, @{{ issue.user.login }}.
          Please follow the issue template, we need more information to reproduce the issue.

          Either a complete code snippet (if more than one file is needed, provide a GitHub repo and instructions to run the code), the specific versions used, or a more detailed description to help us understand the issue.

          Reply to this issuee when all information is provided, thank you.
  - name: enhancement
    labeled:
      issue:
        body: |
          Thank you for setting this as an enhancement. One of the product folk will triage this again to help see when we can fit this in an upcoming sprint.
