name: "Bug Report"
description: "File a bug report to help us improve Nightwatch."
body:
  - type: "markdown"
    attributes:
      value: |
        Before submitting a new issue, try searching for a similar one here: https://github.com/nightwatchjs/nightwatch/search?type=Issues.
  - type: "input"
    id: "description"
    attributes:
      label: "Description of the bug/issue"
      description: "A brief description of the issue, how to reproduce it, and the expected behavior."
      placeholder: |
        When I ____, I expected ____ to happen but ____ happened instead.
    validations:
      required: true
  - type: "textarea"
    id: "steps"
    attributes:
      label: "Steps to reproduce"
      description: |
        Explain how to cause the issue in the provided reproduction.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: textarea
    id: "sample-test"
    attributes:
      label: "Sample test"
      description:
        Include a sample test that reproduces the problem you're experiencing. If possible, the test should be against a public URL.

        Please add the test and other info inline, not as attachments or screenshots.
      placeholder: |
        ```js
        // Please add the sample test here

        module.exports = {
          sampleTest: function() {
            browser
              .navigateTo('<URL here>')
              .click('<selector>')
              .end();
          }
        }
        ```
  - type: input
    id: "run-with-command"
    attributes:
      label: "Command to run"
      description: "Include the command used to run the test."
      placeholder: |
        nightwatch test/sampleTest.js --your-other-arguments-here
  - type: textarea
    id: "verbose-output"
    attributes:
      label: "Verbose Output"
      description: |
        "Extended nightwatch command logging during the session. 
        Please use `nightwatch --verbose` and paste the output here"
      placeholder: |
        ```sh
        [Sample Test] Test Suite
        ────────────────────────────────────────────────────────
        ⠋ Starting ChromeDriver on port 9515...
          Request POST /session
          {
            desiredCapabilities: {
              browserName: 'chrome',
              'goog:chromeOptions': { w3c: true, args: [] },
              name: 'Sample Test'
            },
            capabilities: {
              alwaysMatch: {
                browserName: 'chrome',
                'goog:chromeOptions': { w3c: true, args: [] }
              }
            }
        ⠸ Starting ChromeDriver on port 9515...
        ```
  - type: textarea
    id: "configuration"
    attributes:
      label: "Nightwatch Configuration"
      description: "Add your nightwatch.json or nightwatch.conf.js here; Make sure to leave out any sensitive details."
      placeholder: |
        //
        // Refer to the online docs for more details:
        // https://nightwatchjs.org/gettingstarted/configuration/
        //
        //  _   _  _         _      _                     _          _
        // | \ | |(_)       | |    | |                   | |        | |
        // |  \| | _   __ _ | |__  | |_ __      __  __ _ | |_   ___ | |__
        // | . ` || | / _` || '_ \ | __|\ \ /\ / / / _` || __| / __|| '_ \
        // | |\  || || (_| || | | || |_  \ V  V / | (_| || |_ | (__ | | | |
        // \_| \_/|_| \__, ||_| |_| \__|  \_/\_/   \__,_| \__| \___||_| |_|
        //             __/ |
        //            |___/
        //
        module.exports = {
          src_folders: [],
          page_objects_path: [],
          custom_commands_path: [],
          custom_assertions_path: '',
          plugins: [],
          globals_path: '',
          webdriver: {},
          test_settings: {}
        }
    validations:
      required: true
  - type: "markdown"
    attributes:
      value: |
        ## Your Environment
        Include the relevant details related to your environment.
  - type: "input"
    id: "nightwatch-version"
    attributes:
      label: "Nightwatch.js Version"
      description: "The version of Nightwatch you use."
      placeholder: "2.1.7"
    validations:
      required: true
  - type: "input"
    id: "npm-version"
    attributes:
      label: "NPM Version"
      description: "The version of NPM you use."
      placeholder: "8.12.1"
    validations:
      required: true
  - type: "input"
    id: "node-version"
    attributes:
      label: "Node Version"
      description: "The version of Node you use."
      placeholder: "14.0.0"
  - type: "input"
    id: "yarn-version"
    attributes:
      label: "Yarn Version"
      description: "The version of Yarn you use."
      placeholder: "1.0.1"
  - type: "checkboxes"
    id: "browser"
    attributes:
      label: "Browser"
      description: "The browser(s) this issue occurred with."
      options:
        - label: "Google Chrome"
        - label: "Firefox"
        - label: "Safari"
  - type: "checkboxes"
    id: "operating-system"
    attributes:
      label: "Operating System"
      description: "The operating system(s) this issue occurred with."
      options:
        - label: "macOS"
        - label: "Windows"
        - label: "Linux"
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: |
        Use this section to provide any additional information you might have
        like screenshots, notes, or links to ideas.
