// Generated by CoffeeScript 1.7.1
(function() {
  var Command;

  Command = (function() {
    function Command() {}

    Command.prototype.command = function() {};

    return Command;

  })();

  module.exports = Command;

}).call(this);
