# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coverage Job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run eslint
    - run: npm run mocha-coverage
    - run: npm run text-lcov-coverage
    - run: npm run coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_ACCESS_TOKEN }}
        files: ./coverage/mocha_coverage.lcov
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: codecov_report.txt
        verbose: false

    - name: upload coverage to codeclimate
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: fd95ac5340c6e2e9d45cd50bcd56131f9097f68f95771c256e1a7c89ebb67787
      with:
        coverageCommand: npm run coverage
        debug: false
