name: Type Declaration Tests

on:
  push:
    branches: [main, feat/types-test]
  pull_request:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        typescript-version: ${{ steps.get_typescript_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get TypeScript Version
        id: get_typescript_version
        run: |
          npm install --save-dev @definitelytyped/typescript-versions
          echo "::set-output name=version::$(node -p 'require("@definitelytyped/typescript-versions").TypeScriptVersion.shipped')"
      - name: Install TypeScript
        run: npm install -g typescript@${{ matrix.typescript-version }}
      - name: Install Dependencies
        run: npm ci
      - run: npm run test:types
